name: Binary Extractor

on:
  schedule:
    - cron: "0 12 */7 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Start
        run: echo Starting...

      - name: Get Version
        id: get_ver
        run: |
          latest=$(wget -qO- "https://api.github.com/repos/dani-garcia/vaultwarden/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
          current=$(wget -qO- "https://api.github.com/repos/${{env.GITHUB_REPOSITORY}}/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')
          echo "latest=$latest" >> $GITHUB_OUTPUT
          echo "current=$current" >> $GITHUB_OUTPUT

      - name: Extract
        run: |
          wget https://raw.githubusercontent.com/jjlin/docker-image-extract/main/docker-image-extract
          chmod +x docker-image-extract
          ./docker-image-extract vaultwarden/server:alpine
          ls -ld output/{vaultwarden,web-vault}

      - name: Compress
        run: |
          tar -czvf ${{steps.get_ver.outputs.latest}}.tar.gz output/{vaultwarden,web-vault}
          ls -ld ${{steps.get_ver.outputs.latest}}.tar.gz

      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{steps.get_ver.outputs.latest != steps.get_ver.outputs.current}}
        with:
          tag_name: ${{steps.get_ver.outputs.latest}}
          name: ${{steps.get_ver.outputs.latest}}
          files: ${{steps.get_ver.outputs.latest}}.tar.gz
